language:
  - node_js

node_js:
  - stable
  - '4.2'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'

after_script:
  - npm run cover

deploy:
  on:
    branch: master
    node: stable
  provider: npm
  email: hello@smartcar.com
  api_key: $NPM_API_TOKEN
