language:
  - node_js

node_js:
  - "10"
  - "8"
  - "6"

cache:
  directories:
    - "$HOME/.npm"
    - ".eslintcache"

if: tag IS blank # do not build tags

before_install:
  - dpkg --compare-versions `npm -v` ge 6.0 || npm i -g npm@latest

install:
  - if [[ "$TRAVIS_BRANCH" = "greenkeeper/"* ]]; then npm install; else npm ci; fi

before_script:
  - greenkeeper-lockfile-update

script:
  - npm test
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
 - greenkeeper-lockfile-upload

jobs:
  include:
    - stage: publish
      node_js: 8
      script: npm run release
