language:
  - node_js

node_js:
  - stable
  - '4.2'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'

after_success:
  - npm run cover
  - test $TRAVIS_NODE_VERSION = 'stable' && bash <(curl -s https://codecov.io/bash)

deploy:
  on:
    branch: master
    node: stable
  provider: npm
  email: hello@smartcar.com
  api_key: $NPM_API_TOKEN
